@api = http://localhost:4000

POST {{api}}/login
Content-Type: application/json

{
    "username": "Luis",
    "password": "12345"
}

###

POST {{api}}/createUser
Content-Type: application/json

{
    "username": "Luis",
    "password": "12345",
    "role": "admin"
}

